### ISSUE TITLE
Writing extra information out to Slack?

### ISSUE THREAD

**Issue by jpek42** [jrjackso/CCNetSlackPublisher#6]
Hi -

Question: currently the information written about a build into Slack is minimal. It would be nice to be able to provide additional information, e.g., a pointer to the deployed output.

Is anything in the works to do this? If not, perhaps this is something that I could contribute. If you have ideas on this, would love to get your feedback.

Thanks!

**Comment by jrjackso** [comment]
That would be great if you tossed over a merge request for that. I went pretty bare bones to start because it served my needs, but I was hoping people would add a few things. Thanks for offering to help out.

**Comment by gakera** [comment]
I was also wondering if it would be possible to include a prebuild notification, like a "Build <bla> started" - so that the channel I pipe this into, which also pipes bitbucket commits, would be a more complete list of what is in each build. So far the commits that come after a build is started (if any) can be mistaken for being included in the Success :white_check_mark: notifications.

**Comment by gakera** [comment]
Also, TIL you can include Slack emojis in Github comments :rocket:
